language: python
sudo: false
python:
- '3.4'
install: python setup.py develop
script: python setup.py test
deploy:
  provider: pypi
  user: alynn
  on:
    tags: true
    all_branches: true
  password:
    secure: f9Qlsme1aNar/y8K3zpLDSOZNXHZl7g24A03SUCUObA12wWHGTBuTfq2j/ZJrUy75y7Eemlj66iB2ZaDzbDGIqCphNhHo6fiV/dWzGsiLNYMX0POQRFDTXOzm64ftzh2nBjYM2N87aRyiGnNrQMBNRGc4cyn8yqiKQGSBL4mZB8=
